

#pragma warning disable 1591
#pragma warning disable 0108

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using Glass.Mapper;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Data;
using Sitecore.Data.Items;
using Sitecore.Globalization;

namespace Greenstreet.Feature.Navigation.Models
{
	public partial interface IGlassBase
	{	
		Item Parent { get; }

        IEnumerable<Item> Children { get; }
	}

	[ExcludeFromCodeCoverage]
	public abstract partial class GlassBase : IGlassBase
	{
		[SitecoreId]
        public virtual Guid Id { get; private set; }

        [SitecoreParent]
        public virtual Item Parent { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual GlassLazy<Language> LazyLanguage { get; private set; }

        public virtual Language Language { get { return this.LazyLanguage.Value; } }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual GlassLazy<int> LazyVersion { get; private set; }

        public virtual int Version { get { return this.LazyVersion.Value; } }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual GlassLazy<string> LazyUrl { get; private set; }

        public virtual string Url { get { return this.LazyUrl.Value; } }    

        [SitecoreInfo(SitecoreInfoType.Name)]
        public virtual string Name { get; private set;}

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        public virtual string DisplayName { get; private set; }    

        [SitecoreInfo(SitecoreInfoType.Path)]
        public virtual GlassLazy<string> LazyPath { get; private set; }

        public virtual string Path { get { return this.LazyPath.Value; } }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        public virtual GlassLazy<string> LazyFullPath { get; private set; }        

        public virtual string FullPath { get { return this.LazyFullPath.Value; } }    

        [SitecoreItem]
        public virtual Item Item { get; private set; }

        [SitecoreChildren]
        public virtual IEnumerable<Item> Children { get; private set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        public virtual GlassLazy<IEnumerable<Guid>> LazyBaseTemplateIds { get; private set; }

        public virtual IEnumerable<Guid> BaseTemplateIds { get { return this.LazyBaseTemplateIds.Value; } }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid ItemTemplateId { get; private set; }

        public GlassBase() {}

        public GlassBase(Guid id)
        {
            this.Id = id;
        }

        /// <summary>
        /// Returns a bool indicating if the item inherits the given template
        /// </summary>
        /// <param name="templateGuid">Template Guid</param>
        /// <returns>True if the item is or inherits from a template</returns>
        public bool InheritsTemplate(Guid templateGuid)
        {
            return this.BaseTemplateIds.Contains(templateGuid) || this.ItemTemplateId.Equals(templateGuid);
        }

        /// <summary>
        /// Returns a bool indicating if the item inherits the given template
        /// </summary>
        /// <param name="templateId">Template ID</param>
        /// <returns>True if the item is or inherits from a template</returns>
        public bool InheritsTemplate(ID templateId)
        {
            return this.BaseTemplateIds.Contains(templateId.Guid) || this.ItemTemplateId.Equals(templateId.Guid);
        }
	}

    [SitecoreType(TemplateId = "{962B53C4-F93B-4DF9-9821-415C867B8903}")]
    [ExcludeFromCodeCoverage]
    public class MediaFile : GlassBase 
    {
        [SitecoreInfo(SitecoreInfoType.MediaUrl)]
        public new string Url { get; private set;}
   
        [SitecoreField("Attachment")]
        public virtual Stream File { get; set; }
        
        [SitecoreField("File Path")]
        public virtual string FilePath { get; set; }

        [SitecoreField("Mime Type")]
        public virtual string MimeType { get; set; }

        [SitecoreField("Title")]
        public virtual string Title { get; set; }

        [SitecoreField("Format")]
        public virtual string Format { get; set; }

        [SitecoreField("Description")]
        public virtual string Description { get; set; }
        
        [SitecoreField("Keywords")]
        public virtual string Keywords { get; set; }

        [SitecoreField("Extension")]
        public virtual string Extension { get; set; }
    }
    
    [SitecoreType(TemplateId = "{6D1CD897-1936-4A3A-A511-289A94C2A7B1}")]
    [ExcludeFromCodeCoverage]
    public class DictionaryEntry : GlassBase 
    {
        [SitecoreField("Key")]
        public virtual string Key { get; private set;}
   
        [SitecoreField("Phrase")]
        public virtual string Phrase { get; set; }
    }
}

namespace Greenstreet.Feature.Navigation.Models.GreenStreet.Feature.Navigation.ContentTypes
{
	/// <summary>
	/// IMenuItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Content Types/Menu Item</para>	
	/// <para>ID: 29a7eb5a-e795-4986-9493-e3026d326420</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuItemConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMenuItem : IGlassBase 
	{
		/// <summary>
		/// The Link field.
		/// <para></para>
		/// <para>Field Type: General Link</para>		
		/// <para>Field ID: bffcae47-f469-41dd-9e87-703a16f6d5d7</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(IMenuItemConstants.LinkFieldName)]
		Link Link  { get; set; }

		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: f10aca16-ef53-4ddf-ad1c-b2f6530f7037</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(IMenuItemConstants.TitleFieldName)]
		string Title  { get; set; }

	}

	[ExcludeFromCodeCoverage]
	public static partial class IMenuItemConstants
	{
		public const string TemplateIdString = "29A7EB5A-E795-4986-9493-E3026D326420";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Menu Item";

		public const string LinkFieldIdRaw = "bffcae47-f469-41dd-9e87-703a16f6d5d7";
		public static readonly ID LinkFieldId = new ID("bffcae47-f469-41dd-9e87-703a16f6d5d7");
		public const string LinkFieldName = "Link";

		public const string TitleFieldIdRaw = "f10aca16-ef53-4ddf-ad1c-b2f6530f7037";
		public static readonly ID TitleFieldId = new ID("f10aca16-ef53-4ddf-ad1c-b2f6530f7037");
		public const string TitleFieldName = "Title";

	}

	/// <summary>
	/// MenuItem
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Content Types/Menu Item</para>	
	/// <para>ID: 29a7eb5a-e795-4986-9493-e3026d326420</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuItemConstants.TemplateIdString)] //, Cachable = true
	[ExcludeFromCodeCoverage]
	public partial class MenuItem  : GlassBase, IMenuItem 
	{
		public MenuItem () : base(){}

		public MenuItem (Guid id) : base(id){}


		/// <summary>
		/// The Link field.
		/// <para></para>
		/// <para>Field Type: General Link</para>        
		/// <para>Field ID: bffcae47-f469-41dd-9e87-703a16f6d5d7</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IMenuItemConstants.LinkFieldIdRaw)]
		public virtual Link Link  {get; set;} 
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>        
		/// <para>Field ID: f10aca16-ef53-4ddf-ad1c-b2f6530f7037</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IMenuItemConstants.TitleFieldIdRaw)]
		public virtual string Title  {get; set;} 
    }
}
namespace Greenstreet.Feature.Navigation.Models.GreenStreet.Feature.Navigation.ContentTypes
{
	/// <summary>
	/// IMenuGroup Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Content Types/Menu Group</para>	
	/// <para>ID: 5fd88f0d-24ca-464e-8199-366e47dd01e4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuGroupConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMenuGroup : IGlassBase 
	{
		/// <summary>
		/// The Link field.
		/// <para></para>
		/// <para>Field Type: General Link</para>		
		/// <para>Field ID: 84454bc7-cee6-44ab-aacd-f6da53e0f90c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(IMenuGroupConstants.LinkFieldName)]
		Link Link  { get; set; }

		/// <summary>
		/// The Menu Items field.
		/// <para></para>
		/// <para>Field Type: Multilist</para>		
		/// <para>Field ID: 1c2a1522-3710-40cc-8bdf-9fb675d4cb0d</para>
		/// <para>Custom Data: generic=MenuItem</para>
		/// </summary>
		[SitecoreField(IMenuGroupConstants.MenuItemsFieldName)]
		IEnumerable<MenuItem> MenuItems  { get; set; }

		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 1d330125-f58b-4554-aa95-f13bc65bde92</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[SitecoreField(IMenuGroupConstants.TitleFieldName)]
		string Title  { get; set; }

	}

	[ExcludeFromCodeCoverage]
	public static partial class IMenuGroupConstants
	{
		public const string TemplateIdString = "5FD88F0D-24CA-464E-8199-366E47DD01E4";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Menu Group";

		public const string LinkFieldIdRaw = "84454bc7-cee6-44ab-aacd-f6da53e0f90c";
		public static readonly ID LinkFieldId = new ID("84454bc7-cee6-44ab-aacd-f6da53e0f90c");
		public const string LinkFieldName = "Link";

		public const string MenuItemsFieldIdRaw = "1c2a1522-3710-40cc-8bdf-9fb675d4cb0d";
		public static readonly ID MenuItemsFieldId = new ID("1c2a1522-3710-40cc-8bdf-9fb675d4cb0d");
		public const string MenuItemsFieldName = "Menu Items";

		public const string TitleFieldIdRaw = "1d330125-f58b-4554-aa95-f13bc65bde92";
		public static readonly ID TitleFieldId = new ID("1d330125-f58b-4554-aa95-f13bc65bde92");
		public const string TitleFieldName = "Title";

	}

	/// <summary>
	/// MenuGroup
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Content Types/Menu Group</para>	
	/// <para>ID: 5fd88f0d-24ca-464e-8199-366e47dd01e4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuGroupConstants.TemplateIdString)] //, Cachable = true
	[ExcludeFromCodeCoverage]
	public partial class MenuGroup  : GlassBase, IMenuGroup 
	{
		public MenuGroup () : base(){}

		public MenuGroup (Guid id) : base(id){}


		/// <summary>
		/// The Link field.
		/// <para></para>
		/// <para>Field Type: General Link</para>        
		/// <para>Field ID: 84454bc7-cee6-44ab-aacd-f6da53e0f90c</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IMenuGroupConstants.LinkFieldIdRaw)]
		public virtual Link Link  {get; set;} 
		/// <summary>
		/// The Menu Items field.
		/// <para></para>
		/// <para>Field Type: Multilist</para>        
		/// <para>Field ID: 1c2a1522-3710-40cc-8bdf-9fb675d4cb0d</para>
		/// <para>Custom Data: generic=MenuItem</para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IMenuGroupConstants.MenuItemsFieldIdRaw)]
		public virtual IEnumerable<MenuItem> MenuItems  {get; set;} 
		/// <summary>
		/// The Title field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>        
		/// <para>Field ID: 1d330125-f58b-4554-aa95-f13bc65bde92</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
		[SitecoreField(IMenuGroupConstants.TitleFieldIdRaw)]
		public virtual string Title  {get; set;} 
    }
}
namespace Greenstreet.Feature.Navigation.Models.GreenStreet.Feature.Navigation.Folders
{
	/// <summary>
	/// IMenuFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Folders/Menu Folder</para>	
	/// <para>ID: 659f2859-2ccc-4d7e-acd2-9f34f2e20386</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuFolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMenuFolder : IGlassBase 
	{
	}

	[ExcludeFromCodeCoverage]
	public static partial class IMenuFolderConstants
	{
		public const string TemplateIdString = "659F2859-2CCC-4D7E-ACD2-9F34F2E20386";
		public static readonly ID TemplateId = new ID(TemplateIdString);
		public const string TemplateName = "Menu Folder";

	}

	/// <summary>
	/// MenuFolder
	/// <para></para>
	/// <para>Path: /sitecore/templates/GreenStreet/Feature/Navigation/Folders/Menu Folder</para>	
	/// <para>ID: 659f2859-2ccc-4d7e-acd2-9f34f2e20386</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMenuFolderConstants.TemplateIdString)] //, Cachable = true
	[ExcludeFromCodeCoverage]
	public partial class MenuFolder  : GlassBase, IMenuFolder 
	{
		public MenuFolder () : base(){}

		public MenuFolder (Guid id) : base(id){}


    }
}
